apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-monitoring
  namespace: monitoring
spec:
  acme:
    email: your-email@example.com  # UPDATE THIS with your email
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt-monitoring-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
